services:
  app:
    container_name: ridequest_app
    image: ridequest_app:local
    build:
      context: ./app
    ports:
      - "5173:5173"
    expose:
      - "5173"
    volumes:
      - ./app/src:/app/src
    environment:
      VITE_STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy

  api:
    container_name: ridequest_api
    image: ridequest_api:local
    build:
      context: ./api
    ports:
      - "5174:5174"
    expose:
      - "5174"
    volumes:
      - ./api/src:/api/src
    environment:
      STRAVA_CLIENT_ID: ${VITE_STRAVA_CLIENT_ID}
      #TODO other env vars
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [CMD, curl, -s, -f, "http://localhost:5174/api/v1/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 3

  db:
    container_name: ridequest_db
    image: postgres:17.6-alpine3.22
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [CMD, pg_isready, -h, localhost, -p, "5432"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db:
